feat: add start/end logic for reward emissions
morpho-org/morpho-blue-rewards-emissions pull request #15
Opened 2024-01-30 16:19 UTC by yum0e

2024-01-31 09:08 UTC, julien-devatom requested changes

2024-01-31 09:08 UTC, julien-devatom commented on src/TimedEmissionDataProvider.sol
> +    event TimedRewardsEmissionSet(
add the `timedRewardsEmissionId` as an indexed field in the event.

2024-01-31 09:08 UTC, julien-devatom commented on src/TimedEmissionDataProvider.sol
> +        bytes32 timedRewardsEmissionId = keccak256(abi.encode(msg.sender, urd, rewardToken, market));
I suggest you to create a getId pure function that integrators can use externally.

2024-01-31 09:08 UTC, julien-devatom commented on src/TimedEmissionDataProvider.sol
> +    /// @param urd The URD distributing the rewards.
```suggestion
    /// @param urd The URD that should redistribute the rewards.
```

2024-01-31 09:08 UTC, julien-devatom commented on test/TimedEmissionDataProvider.t.sol
> +    function testSetRewardsShouldRevertWhenSameCallerWantsToUpdateTheSameEmission(
do the same test but with a different emission, to test that an emission cannot be overriden by a different one.

2024-01-31 09:48 UTC, Jean-Grimal requested changes

2024-01-31 09:48 UTC, Jean-Grimal commented on src/TimedEmissionDataProvider.sol
> +    event TimedRewardsEmissionSet(
And remove the sender ?

2024-01-31 09:48 UTC, Jean-Grimal commented on src/TimedEmissionDataProvider.sol
> +        require(timedRewardsEmission.startTimestamp >= block.timestamp, ErrorsLib.START_TIMESTAMP_IN_THE_PAST);
```suggestion
        require(timedRewardsEmission.startTimestamp >= block.timestamp, ErrorsLib.START_TIMESTAMP_OUTDATED);
```

2024-01-31 09:48 UTC, Jean-Grimal commented on src/TimedEmissionDataProvider.sol
> +            timedRewardsEmission.endTimestamp > timedRewardsEmission.startTimestamp, ErrorsLib.END_TIMESTAMP_TOO_EARLY
```suggestion
            timedRewardsEmission.endTimestamp > timedRewardsEmission.startTimestamp, ErrorsLib.END_TIMESTAMP_INVALID
```

2024-01-31 09:49 UTC, yum0e commented on src/TimedEmissionDataProvider.sol
> +    event TimedRewardsEmissionSet(
I wonder if this is better as far as I can't index more than 3 args in an event. I feel like searching an event for a particular `rewardToken`, `market` or `sender` is better than with the `timedRewardsEmissionId` that acts as a simple way of mapping rewards emission inside the contract. As far as I will also add a simple getter function to abstract the id computation, I feel like it is suboptimal for the user/dev if we index the event by the id. Wdyt?

2024-01-31 10:52 UTC, julien-devatom commented on src/TimedEmissionDataProvider.sol
> +    event TimedRewardsEmissionSet(
I agree with you since if you have access to the id, all the data can be read directly in the contract.

2024-01-31 10:53 UTC, julien-devatom commented on src/TimedEmissionDataProvider.sol
> +    event TimedRewardsEmissionSet(
@Jean-Grimal wdym by "remove the sender"? Rm from the event or just from indexing?

It's a requirement to have it in the event since it permits us to link a rate submitter to an address, that is a hard requirement since contract is permissionless

2024-01-31 10:56 UTC, yum0e commented on src/TimedEmissionDataProvider.sol
> +    event TimedRewardsEmissionSet(
I did a simple getter function that abstract the complexity for the dev/user wishing to query his rewards emission as if he was using a mapping, it also improves test readability in my opinion by returning the struct. The id is only meaningful in the contract to have a nice way of preventing emission overrides.

2024-01-31 11:15 UTC, Jean-Grimal commented on src/TimedEmissionDataProvider.sol
> +    event TimedRewardsEmissionSet(
> @Jean-Grimal wdym by "remove the sender"? Rm from the event or just from indexing?
> 
> It's a requirement to have it in the event since it permits us to link a rate submitter to an address, that is a hard requirement since contract is permissionless

Just remove from indexing. That was a suggestion if the `timedRewardsEmissionId` needs to be indexed

2024-02-13 08:27 UTC, Rubilmax commented on src/TimedEmissionDataProvider.sol
> +    mapping(bytes32 timedRewardsEmissionId => TimedRewardsEmission) public timedRewardsEmissions;
```suggestion
    mapping(bytes32 id => TimedRewardsEmission) public emission;
```
1. `id` is not ambiguous in this context (just like it is not in morpho-blue's context), thanks to the natspec above and because market ids are named "market" in this contract
2. `emission` is singular because that is the convention we went for in morpho-blue

2024-02-13 08:27 UTC, Rubilmax commented on src/TimedEmissionDataProvider.sol
> +    function _computeTimeRewardsEmissionId(address caller, address urd, address rewardToken, Id market)
```suggestion
    function _id(address caller, address urd, address rewardToken, Id market)
```

2024-02-13 08:27 UTC, Rubilmax commented on src/TimedEmissionDataProvider.sol
> +struct TimedRewardsEmission {
```suggestion
struct Emission {
```

2024-02-13 08:27 UTC, Rubilmax commented on src/TimedEmissionDataProvider.sol
> +        emit TimedRewardsEmissionSet(rewardToken, market, msg.sender, urd, timedRewardsEmission);
Anyone can set an emission:
1. how are integrators (including) us supposed to query emissions offchain? It is required from them to whitelist ids right?
2. how are integrators supposed to query emissions onchain? It is required from them to whitelist ids (or specific id components, the other being constant for them) right?
3. What's the benefit of this design over a completely offchain rate API?

2024-02-13 08:27 UTC, Rubilmax commented on src/TimedEmissionDataProvider.sol
> +    mapping(bytes32 timedRewardsEmissionId => TimedRewardsEmission) public timedRewardsEmissions;
to be discussed

2024-02-13 09:33 UTC, Rubilmax commented on src/TimedEmissionDataProvider.sol
> +        emit TimedRewardsEmissionSet(rewardToken, market, msg.sender, urd, timedRewardsEmission);
I have the answer to 1: https://github.com/morpho-org/morpho-blue-rewards-subgraph/blob/main/src/handlers/emission-data-provider.ts

2024-02-15 10:38 UTC, yum0e commented on src/TimedEmissionDataProvider.sol
> +    mapping(bytes32 timedRewardsEmissionId => TimedRewardsEmission) public timedRewardsEmissions;
Added your change about the `id` but kept the `programs` plural since we now map to an array from an id.

2024-02-16 10:40 UTC, Jean-Grimal commented on src/BlueMarketRewardsProgramRegistry.sol
> +    uint256 public constant MAX_PROGRAMS_WITH_SAME_ID = 100;
This number seems huge
We really think there could be 100 different distributions with the same sender, urd, market and reward token ?

2024-02-16 18:19 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +    uint256 public constant MAX_PROGRAMS_WITH_SAME_ID = 100;
I think that we need to come up with a reasonable number to allow enough bandwidth for projects while not querying too large arrays from the getter function. 
Needs to be discussed but maybe around 10 or 20 slots maximum can be enough indeed. Wdyt?

2024-02-20 10:56 UTC, julien-devatom requested changes

2024-02-20 10:56 UTC, julien-devatom commented on src/BlueMarketRewardsProgramRegistry.sol
> +        uint256 length = programs[programId].length;
add a getter to retrieve the array length, since this is not feasible offchain

2024-02-20 10:56 UTC, julien-devatom commented on src/BlueMarketRewardsProgramRegistry.sol
> +            }
so you are not mapping the other values and a program can be defined twice:
- I set a program at position 0 in the list to start=now, end = now + 1
- I set up another program at position 1: start = now + 1000, end = start + 1
- In 1 second, I resend the same tx as the previous one. Now I have 2 identical programs: one at position 0 & one at position 1.

2024-02-20 10:56 UTC, julien-devatom commented on src/BlueMarketRewardsProgramRegistry.sol
> +    uint256 public constant MAX_PROGRAMS_WITH_SAME_ID = 100;
I suggest to use the same value as metamorpho market queues: [30](https://github.com/morpho-org/metamorpho/blob/main/src/libraries/ConstantsLib.sol#L16)

2024-02-20 10:56 UTC, julien-devatom commented on src/BlueMarketRewardsProgramRegistry.sol
> +            }
I suggest to never override programs.

2024-02-20 10:56 UTC, julien-devatom commented on src/BlueMarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[MAX_PROGRAMS_WITH_SAME_ID]) public programs;
I dont know if you're warming all the cold slots but it can be really expensive to do something like that. We are not initializing the size in Metamorpho but idk, I'll let on-chain engineers answer this one.

2024-02-20 10:56 UTC, julien-devatom commented on src/BlueMarketRewardsProgramRegistry.sol
> +            }
we can also precise in the readme that: 
- programs are not ordered in the array.
- a program can be defined only once. 
- max number of programs per (urd, sender, rewardToken, market) is 30

2024-02-20 12:40 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +            }
> so you are not mapping the other values and a program can be defined twice:
> 
> * I set a program at position 0 in the list to start=now, end = now + 1
> * I set up another program at position 1: start = now + 1000, end = start + 1
> * In 1 second, I resend the same tx as the previous one. Now I have 2 identical programs: one at position 0 & one at position 1.
I don't see the issue here, if someone wants to do two identical programs he is free to do it since it is impossible to delete a program. 

> I suggest to never override programs.
It simplifies the logic and I feel like 30 slots is enough. I agree with you 👍

2024-02-20 13:16 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[MAX_PROGRAMS_WITH_SAME_ID]) public programs;
Also curious about the trade offs and happy to change if it's gas expensive.

2024-02-21 07:55 UTC, Rubilmax requested changes

2024-02-21 07:55 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[MAX_PROGRAMS_WITH_SAME_ID]) public programs;
So I found this trick clever but I believe you are not using it optimally because of `getArrayLength` which reads all the slots of the array

I would suggest to instead store a dynamic array (which stores the length at the first slot) and have an invariant that checks `length < MAX_PROGRAMS_WITH_SAME_ID` whenever you add one

2024-02-21 07:55 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +    /// Where id = keccak256(abi.encode(msg.sender, urd, rewardToken, market)).
```suggestion
    /// Where id = keccak256(abi.encode(owner, urd, rewardToken, market)).
```

2024-02-21 07:55 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[MAX_PROGRAMS_WITH_SAME_ID]) public programs;
```suggestion
    mapping(bytes32 id => MarketRewardsProgram[]) public programs;
```

2024-02-21 07:55 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +        uint8 length = getArrayLength(programId);
```suggestion
        MarketRewardsProgram[] programSet = programs[programId];
```

btw the fact that you name `programId` the id that points to a list of `MarketRewardsProgram` makes the naming ambiguous. I would suggest either don't name each element a "program" (e.g. "distribution") or call the array of programs a "programSet" or i don't know

2024-02-21 07:55 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +        if (length == MAX_PROGRAMS_WITH_SAME_ID) {
```suggestion
        if (programSet.length == MAX_PROGRAMS_WITH_SAME_ID) {
```

2024-02-21 07:55 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +        programs[programId][length] = program;
```suggestion
        programSet.push(program);
```

2024-02-21 08:57 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[MAX_PROGRAMS_WITH_SAME_ID]) public programs;
Seems indeed like a better way to do it, it simplifies the code, thanks!

2024-02-21 08:58 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +        uint8 length = getArrayLength(programId);
I was struggling with the naming indeed, I think that calling it `id` and manipulating a set is a nice to do, thanks!

2024-02-21 10:09 UTC, Rubilmax reviewed
seems great!

2024-02-21 10:09 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[]) public programs;
Just to make sure this is intended: this creates a `programs(bytes32 id, uint256 index)` getter, which will return a zero-ed out program for each index >= MAX_PROGRAMS_WITH_SAME_ID

I believe it is fine, because it is overkill to revert instead

2024-02-21 10:09 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +    function getNumberOfProgramsForId(bytes32 id) public view returns (uint8) {
```suggestion
    function getNbProgramsForId(bytes32 id) public view returns (uint8) {
```

2024-02-21 10:09 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +    }
This contract has a `Multicall`, so it seems this function could be replaced with a multicall of `programs(id, index)` for `index <= nbProgramsForId(id)`

So this function seems to only exist for simplicity ; maybe overkill

2024-02-21 14:31 UTC, julien-devatom commented on src/BlueMarketRewardsProgramRegistry.sol
> +    }
Really smart the usage of the multicall, but I would say that its much more easier for end users to fetch them from getPrograms (also we can query it from etherscan)

2024-02-21 15:19 UTC, Rubilmax commented on src/BlueMarketRewardsProgramRegistry.sol
> +    }
I guess it makes sense for such a contract anyway (the goal is not to have the cleanest & minimal code)

2024-02-22 10:41 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +    function getNumberOfProgramsForId(bytes32 id) public view returns (uint8) {
I prefer to stay descriptive, I believe it's a naming preference

2024-02-22 10:43 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +    }
Yep, agree with both of you. Two ways of querying information seems nice depending on the needs.

2024-02-22 10:54 UTC, yum0e commented on test/BlueMarketRewardsProgramRegistry.t.sol
> +    );
When trying, I get a compiler error. What is the benefit of using `BlueMarketRewardsProgramRegistry. ProgramRegistered` instead of this event directly? I don't see any security issue since the contract still needs to emit the same event no?

2024-02-22 11:19 UTC, MerlinEgalite requested changes

2024-02-22 11:19 UTC, MerlinEgalite commented on README.md
> +## BlueMarketRewardsProgramRegistry contract
```suggestion
## MorphoBlueMarketRewardsProgramRegistry contract
```

We always use Morpho with Blue everywhere and we should stick with it.

Could be shorten to `MarketRewardsRegistry` tbh

2024-02-22 11:19 UTC, MerlinEgalite commented on README.md
> +### Rewards Programs Structure
why programs is at plural?

2024-02-22 11:19 UTC, MerlinEgalite commented on README.md
> +- **Discontinuing a Rate**: Rates are ceased when the program's `endTimestamp` is reached.
```suggestion
- **Discontinuing a Rate**: Rates cease when the program's `endTimestamp` is reached.
```

2024-02-22 11:19 UTC, MerlinEgalite commented on src/BlueMarketRewardsProgramRegistry.sol
> +    uint256 endTimestamp;
```suggestion
    uint256 start;
    /// @notice The timestamp at which the rewards program ends.
    uint256 end;
```

2024-02-22 11:19 UTC, MerlinEgalite commented on src/BlueMarketRewardsProgramRegistry.sol
> +    uint256 endTimestamp;
I don't think there's a clash with something else but it's not a blocker at all

2024-02-22 11:19 UTC, MerlinEgalite commented on src/BlueMarketRewardsProgramRegistry.sol
> +    /// @param market The id of Blue market on which rewards are programmed to be distributed..
```suggestion
    /// @param market The id of Blue market on which rewards are programmed to be distributed.
```

2024-02-22 11:19 UTC, MerlinEgalite commented on src/libraries/ErrorsLib.sol
> +// SPDX-License-Identifier: GPL-2.0-or-later
```suggestion
// SPDX-License-Identifier: MIT
```

2024-02-22 11:19 UTC, MerlinEgalite commented on src/BlueMarketRewardsProgramRegistry.sol
> +    function getNumberOfProgramsForId(bytes32 id) public view returns (uint8) {
why do we return a `uint8`?

2024-02-22 11:19 UTC, MerlinEgalite commented on src/BlueMarketRewardsProgramRegistry.sol
> +    function getPrograms(address caller, address urd, address rewardToken, Id market)
i guess to query the list of programs for one specific market will be done at the subgraph level right?

2024-02-22 11:19 UTC, MerlinEgalite commented on src/BlueMarketRewardsProgramRegistry.sol
> +
Missing natspec here

2024-02-22 13:54 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +    function getNumberOfProgramsForId(bytes32 id) public view returns (uint8) {
to stay consistent with `MAX_PROGRAMS_WITH_SAME_ID` type but let's put them both at uint256 then, less overhead for integrators.

2024-02-22 13:55 UTC, yum0e commented on src/BlueMarketRewardsProgramRegistry.sol
> +    function getPrograms(address caller, address urd, address rewardToken, Id market)
exactly

2024-02-22 16:09 UTC, julien-devatom requested changes

2024-02-22 16:09 UTC, julien-devatom commented on README.md
> +- **Program Structure**: The contract is designed to handle multiple rewards programs, each with its own start and end times. Once a program is registered, it is immutable and cannot be updated. Proj
This is only for the `MarketRewardsProgramRegistry`, it should be mentionned

2024-02-22 16:09 UTC, julien-devatom commented on script/DeployMarketRewardsProgramRegistry.s.sol
> +import "src/MarketRewardsProgramRegistry.sol";
```suggestion
import {MarketRewardsProgramRegistry} from "src/MarketRewardsProgramRegistry.sol";
```

2024-02-22 16:09 UTC, julien-devatom commented on src/MarketRewardsProgramRegistry.sol
> +import {Id} from "morpho-blue/interfaces/IMorpho.sol";
```suggestion
import {Id as MarketId} from "morpho-blue/interfaces/IMorpho.sol";
```

I think its better to add an alias because the naming clash with a program id

2024-02-22 16:09 UTC, julien-devatom commented on src/MarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[]) public programs;
```suggestion
    mapping(bytes32 programId => MarketRewardsProgram[]) public programs;
```

2024-02-22 16:09 UTC, julien-devatom commented on src/MarketRewardsProgramRegistry.sol
> +    function _id(address caller, address urd, address rewardToken, Id market) internal pure returns (bytes32) {
```suggestion
    function _programId(address caller, address urd, address rewardToken, Id market) internal pure returns (bytes32) {
```

2024-02-22 16:09 UTC, julien-devatom commented on test/MarketRewardsProgramRegistry.t.sol
> +    function testRegisterShouldRevertWhenendIsBeforestart(MarketRewardsProgram calldata program) public {
```suggestion
    function testRegisterShouldRevertWhenEndIsBeforestart(MarketRewardsProgram calldata program) public {
```

2024-02-22 16:09 UTC, julien-devatom commented on test/MarketRewardsProgramRegistry.t.sol
> +    function testRegisterShouldRevertWhenstartIsInThePast(MarketRewardsProgram calldata program) public {
```suggestion
    function testRegisterShouldRevertWhenStartIsInThePast(MarketRewardsProgram calldata program) public {
```

2024-02-22 16:09 UTC, julien-devatom commented on test/MarketRewardsProgramRegistry.t.sol
You can test to add more than 30 programs

2024-02-23 14:26 UTC, MerlinEgalite commented on src/MarketRewardsProgramRegistry.sol
> +    function _id(address caller, address urd, address rewardToken, Id market) internal pure returns (bytes32) {
_id is enough to me

2024-02-23 14:44 UTC, julien-devatom commented on src/MarketRewardsProgramRegistry.sol
> +    function _id(address caller, address urd, address rewardToken, Id market) internal pure returns (bytes32) {
but Id is market-related, can be confusing 🤔

2024-02-26 10:04 UTC, Rubilmax commented on src/MarketRewardsProgramRegistry.sol
> +    function _id(address caller, address urd, address rewardToken, Id market) internal pure returns (bytes32) {
In this isolate context it's completely fine

2024-02-26 10:05 UTC, Rubilmax approved these changes

2024-02-29 13:25 UTC, yum0e commented on src/MarketRewardsProgramRegistry.sol
> +    mapping(bytes32 id => MarketRewardsProgram[]) public programs;
I let `id` since the function is kept to be `_id` and `Id` is now `MarketId` to avoid confusion

2024-02-29 13:30 UTC, yum0e commented on test/MarketRewardsProgramRegistry.t.sol
This is what I test in the last test

2024-02-29 13:35 UTC, julien-devatom approved these changes

2024-02-29 14:23 UTC, MerlinEgalite approved these changes

2024-03-01 10:36 UTC, Jean-Grimal approved these changes

2024-03-02 20:38 UTC, merged